### ISSUE TITLE
WARNING when running with tslint-config-standard

### ISSUE THREAD

**Issue by BjornMelgaard** [blakeembrey/tslint-config-standard#37]
```
 yr tslint
yarn run v0.28.4
warning package.json: No license field
$ tslint --fix -c tslint.json -p tsconfig.json
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.


Done in 2.31s.
```

**Comment by blakeembrey** [comment]
If you're going to log an issue, please take some time to add a description - I don't know what the expected output is for you, nor what you'd like me to fix.

I'll take a stab anyway. This is correct. If you'd like the warning to go away, you'll need to log an issue with TSLint. These rules are enabled for everyone by default since some people might not have the compiler options enabled (so the rules are there to match Standard.js). You can also disable these rules in your own `tslint.json` file.

**Comment by CoreyCole** [comment]
Just ran into this same issue. The fix for anyone wondering is something like this:
```
{
  "extends": "tslint-config-standard",
  "rules": {
    "no-unused-variable": false
  }
}
```
