### ISSUE TITLE
Code that errors indentation when upgrading from v4 to v7

### ISSUE THREAD

**Issue by QuantumInformation** [blakeembrey/tslint-config-standard#46]
I don't think this indentation error is correct, I didn't get it before

<img width="1161" alt="screen shot 2018-05-22 at 07 32 05" src="https://user-images.githubusercontent.com/216566/40345730-576e1906-5d92-11e8-9135-7aeda6845500.png">

line 319 looks fine to me.

When rolling back to `    "tslint-config-standard": "^4.0.0"` it works fine.

**Comment by blakeembrey** [comment]
When opening an issue, considering copy and pasting the code you have issues with instead of taking a screenshot. People won't be able to correct your issue otherwise, since it's unfair to force someone to go to the effort to recreating the code.

In any case, it looks correct to me. A major version means a breaking change and your indentation looks wrong to me - you have a four space indent below line 312 and the closing parenthesis doesn't align on line 329.
